### ISSUE TITLE
PSD2/SCA ready?

### ISSUE THREAD

**Issue by jjcoffee** [citypay/citypay-paylink-woo-commerce#10]
Just wondering if the plugin is all ready for the new PSD2 regulations that are coming into force in September?

**Comment by garyfeltham** [comment]
The plugin is integrated into Paylink version 3 which will automatically
scale up to 3D-Secure Version 2 when available and will continue to offer
3D-Secure V1.

The 3DSv2 upgrade will depend on the upstream Acquirer and Card Scheme
used. There is suggestion that the September 14th deadline may have some
exemptions as some Acquirers are only just accrediting now.

Gary Feltham
