### ISSUE TITLE
v2.0.7 plugin missing

### ISSUE THREAD

**Issue by alaistair76** [citypay/citypay-paylink-woo-commerce#22]
Hi,

Thanks for releasing v2.0.7 but when we downloaded the release we have noticed that the v2.0.7 plugin zip is missing from the ./dist folder

Thanks

Al & Jonny (from the Refinery)

**Comment by hectorconceicao** [comment]
Hi, 

Sorry for the late reply.

Please find in the dist folder the newest versions. (v2.0.7 included)

[https://github.com/citypay/citypay-paylink-woo-commerce/tree/master/dist](url)

Kind regards.
Hector
